Table.SelectRows(Dados, each [Ano] = 2023)